name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
    - name: "dump github context"
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash
    # - name: "create comment using marketplace job"
    #   uses: peter-evans/create-or-update-comment@v3
    #   with:
    #     issue-number: ${{ github.event.issue.number }} # issue number to be commented upon
    #     body: |
    #       This is a multi-line test comment
    #       - With GitHub **Markdown** :sparkles:
    #       - Created by [create-or-update-comment][1]

    #       [1]: https://github.com/peter-evans/create-or-update-comment
    #     reactions: '+1'

  comment-using-api:
    runs-on: ubuntu-latest
    steps:
    - name: "create comment with api"
      run: |
        gh api -X POST \
            https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body='Comment but from the API call not marketplace actions'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # will be required to call the gh cli command
        ORGANIZATION: ${{ github.event.repository.owner.login }} #JSON structure changed
        REPOSITORY: ${{ github.event.repository.name }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
